channels:
  - defaults
  - conda-forge
dependencies:
  - ipython
  - ipyleaflet
  - ipywidgets
  - geopandas
  - fiona
  - shapely
  - folium
  - branca
  - numpy
  - seaborn
  - matplotlib
  - pandas
  - time
