channels:
  - defaults
  - conda-forge
  - pip
dependencies:
  - ipython
  - sys
  - json
  - ipyleaflet
  - ipywidgets
  - geopandas
  - fiona
  - shapely
  - glob
  - folium
  - branca
  - numpy
  - seaborn
  - matplotlib
  - pandas
  - datetime
  - time
  - math